### ISSUE TITLE
page_loader.c - Pressing <ENTER> 2x during character creation saves empty player name

### ISSUE THREAD

**Issue by Jakubisek** [kerrambit/InterStellar-Pong#40]
[YouTube video](https://youtu.be/pgnzXi4GgIQ)

**Comment by kerrambit** [comment]
@Jakubisek Thank you for reporting the bug.

**Comment by kerrambit** [comment]
**Explanation:**
The reported bug was a symptom of a more general bug.
This "general" bug was caused by the fact that an empty string was evaluated as a valid player name. This made a mess afterwards while writing and reading from the players' file. That led finally to a segfault as seen on the video.

The video shows the specific case when the user first enters a valid name and the name is saved. Then the user presses Enter again and because at the moment the terminal is empty, the new name stored is effectively just an empty string which leads to the problem described above.

The bug was patched.

@Jakubisek Please, retest this issue if possible and let me know if you find some bug. Thank you.
