### ISSUE TITLE
terminal.c & page_loader.c- Unsafe handling of long terminal inputs and hard limit on player's name

### ISSUE THREAD

**Issue by Jakubisek** [kerrambit/InterStellar-Pong#41]
Terminal should not accept input longer than a certain limit (there is no reason the for the user to enter more than 1024 character), since there seems to be no limit entering a large amount of text will crash the program. (this can happen easily with CTRL + SHIFT + V)
I propose that after a certain length of parsed input the terminal reject the rest with an error.
Video documentation: [YouTube](https://youtu.be/Evi1GZs_htc)
> before the video I managed to create a player whose name could not be displayed using the same method shown (but with much less text so the program doesn't crash)

**Comment by kerrambit** [comment]
@Jakubisek Thank you for reporting the issue. In the next week or so, I will investigate the bug you reported. Please, I want to keep in touch with you if I'd need more detailed info. Thank you.

**Comment by kerrambit** [comment]
**Investigation:**

First, I want to see how the program behaves regarding loading big inputs. The attached text file (cca 20 KB) with around 20.5 thousand characters was loaded in 73 seconds on my computer. The loading was accompanied by unpleasant screen flickering. There were no errors, however. The problem happens when such a long string is used as a player's name. In after game page, there is an error ("Process terminating with default action of signal 2 (SIGINT)") regarding the IO writes to the terminal window.

**Fixes**

So, two things needed to be fixed: 1) hard limit on input length and 2) separate hard limit on player's name length.

The hard limit on the player's name length was set to 14 characters since the button used in the player's gallery is not able to display longer names anyway.

The length hard limit of any command was set to 516 characters. Now the hard limit is defined in the source code and can be easily changed if the customer or user finds a reason for that.

@Jakubisek Plese, you can retest the issue if you encounter any strange and unexpected behaviour.

**Attachment**: [long_test_text.txt](https://github.com/kerrambit/InterStellar-Pong/files/12566690/long_test_text.txt)
