### ISSUE TITLE
interstellar_pong.c - Minor visual glitch when hitting asteroid

### ISSUE THREAD

**Issue by Jakubisek** [kerrambit/InterStellar-Pong#43]
The color of the material will flicker for one game frame before it is removed with the color of the next material that will be added (stone will flicker with red/iron if the next spawned material is iron). Since this happens rarely and only for a brief moment I cannot provide video evidence yet.

**Comment by Jakubisek** [comment]
Finally got it on video:
[YouTube](https://youtu.be/kFVMvrE2e3c)

**Comment by kerrambit** [comment]
@Jakubisek Thank you for the detailed analysis. I am aware of this matter. You have convinced me, however, to add this issue to the bug fix for milestone v1.2.0 Bugs.

**Comment by kerrambit** [comment]
The bug should be fixed. The source of it came from the fact, that when the collision was detected, new material and coordinates were generated for the meteor, but the pixel buffer still contained old pixels from the old meteor position and material.

The old meteor coordinates and material were cleared too late - at the beginning of the following frame.

So, the fix was that when the collision is detected, the old pixels of a meteor are cleared instantly.

@Jakubisek If you have anything to it, please feel free to comment.
